apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2  # Two instances
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: esaf12254548/apptest:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_NAME
              value: "App1"
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
