Vagrant.configure("2") do |config|
  config.vm.define "esafouan" do |vm1|
    vm1.vm.box = "hashicorp/bionic64"
    vm1.vm.hostname = "Server"
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.synced_folder "./confs", "/vagrant"

    vm1.vm.provision "shell", path: "./scripts/k3s.sh"

  end

  config.vm.define "esafouan2" do |vm2|
    vm2.vm.box = "hashicorp/bionic64"
    vm2.vm.hostname = "ServerWorker"
    vm2.vm.network "private_network", ip: "192.168.56.111"
    vm2.vm.synced_folder "./confs", "/vagrant"
    vm2.vm.provision "shell", path: "./scripts/k3s-agent.sh"

  end
end
